parameters:
    pimcore_notification_sender: 0
    pimcore_notification_title: "A new product is assigned to you."
    users_query: "SELECT users.id AS userId, users.name AS userName FROM users WHERE users.name <> 'system'"
    products_storage_path: "/Products"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BackendExtBundle\Controller\:
        resource: "../src/Controller"
        public: true
        tags: ["controller.service_arguments"]
