parameters:
    users_query: "SELECT users.id AS userId, users.name AS userName FROM users"
    products_storage_path: "/Products"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BackendExtBundle\Controller\:
        resource: "../src/Controller"
        public: true
        tags: ["controller.service_arguments"]
